name: Datapack_reload
version: '${project.version}'
main: io.github.robot7769.datapack_reload.Reloader
api-version: 1.19
authors: [ Robot7769 ]
description: Datapack reloder without server restart
commands:
  datapackreload:
    description: Reload datapacks without server restart
    usage: /<command>
    aliases: datareload
    permission: datapackreload
    permission-message: You are not allowed to use the command datapackreload.
    cooldown: 5

